# Generated by Django 4.2.10 on 2025-05-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
