# Generated by Django 4.2.10 on 2025-05-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_slug_promotion_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='slug',
        ),
    ]
