# Generated by Django 4.2.10 on 2025-05-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember_is_active_teammember_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='slug',
        ),
    ]
