# Generated by Django 4.2.10 on 2025-05-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='preparation_time',
            field=models.IntegerField(default=15, help_text='Час приготування в хвилинах'),
        ),
    ]
